//
// File generated by /apps/root/5.34.36/root//bin/rootcint at Mon Nov 25 15:22:47 2019

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME srcdIDSTDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "DSTDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void TDST_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_TDST(void *p);
   static void deleteArray_TDST(void *p);
   static void destruct_TDST(void *p);
   static void streamer_TDST(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::TDST*)
   {
      ::TDST *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TDST >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TDST", ::TDST::Class_Version(), "./include/TDST.h", 19,
                  typeid(::TDST), ::ROOT::DefineBehavior(ptr, ptr),
                  &::TDST::Dictionary, isa_proxy, 0,
                  sizeof(::TDST) );
      instance.SetDelete(&delete_TDST);
      instance.SetDeleteArray(&deleteArray_TDST);
      instance.SetDestructor(&destruct_TDST);
      instance.SetStreamerFunc(&streamer_TDST);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::TDST*)
   {
      return GenerateInitInstanceLocal((::TDST*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TDST*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr TDST::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *TDST::Class_Name()
{
   return "TDST";
}

//______________________________________________________________________________
const char *TDST::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TDST*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TDST::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TDST*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TDST::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TDST*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TDST::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TDST*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void TDST::Streamer(TBuffer &R__b)
{
   // Stream an object of class TDST.

   TRootBeer::Streamer(R__b);
}

//______________________________________________________________________________
void TDST::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TDST.
      TClass *R__cl = ::TDST::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fServedBranches[220][6]", &fServedBranches);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fBankType[220]", fBankType);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fBankIndex[220]", fBankIndex);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fRowLength[220]", fRowLength);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fBankList[220][8]", fBankList);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fBankBranch[220][8]", fBankBranch);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fRowTotal[220]", fRowTotal);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fDSTfile", &fDSTfile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fBankTree", &fBankTree);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fBigBuff", &fBigBuff);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fDataStartAddr", &fDataStartAddr);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fDataAddr", &fDataAddr);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fServedBankNo", &fServedBankNo);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fEntry", &fEntry);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fMaxEntry", &fMaxEntry);
      TRootBeer::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_TDST(void *p) {
      delete ((::TDST*)p);
   }
   static void deleteArray_TDST(void *p) {
      delete [] ((::TDST*)p);
   }
   static void destruct_TDST(void *p) {
      typedef ::TDST current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TDST(TBuffer &buf, void *obj) {
      ((::TDST*)obj)->::TDST::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::TDST

/********************************************************
* src/DSTDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableDSTDict();

extern "C" void G__set_cpp_environmentDSTDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("include/TDST.h");
  G__cpp_reset_tagtableDSTDict();
}
#include <new>
extern "C" int G__cpp_dllrevDSTDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TDST */
static int G__DSTDict_174_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TDST* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TDST(
(const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) TDST(
(const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DSTDictLN_TDST));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DSTDict_174_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TDST::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DSTDict_174_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TDST::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DSTDict_174_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TDST::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DSTDict_174_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TDST::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DSTDict_174_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TDST*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DSTDict_174_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TDST::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DSTDict_174_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TDST::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DSTDict_174_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TDST::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DSTDict_174_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TDST::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__DSTDict_174_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TDST* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TDST(*(TDST*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DSTDictLN_TDST));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TDST G__TTDST;
static int G__DSTDict_174_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TDST*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TDST*) (soff+(sizeof(TDST)*i)))->~G__TTDST();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TDST*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TDST*) (soff))->~G__TTDST();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__DSTDict_174_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TDST* dest = (TDST*) G__getstructoffset();
   *dest = *(TDST*) libp->para[0].ref;
   const TDST& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TDST */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncDSTDict {
 public:
  G__Sizep2memfuncDSTDict(): p(&G__Sizep2memfuncDSTDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncDSTDict::*p)();
};

size_t G__get_sizep2memfuncDSTDict()
{
  G__Sizep2memfuncDSTDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceDSTDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DSTDictLN_TDST))) {
     TDST *G__Lderived;
     G__Lderived=(TDST*)0x1000;
     {
       TRootBeer *G__Lpbase=(TRootBeer*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DSTDictLN_TDST),G__get_linked_tagnum(&G__DSTDictLN_TRootBeer),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DSTDictLN_TDST),G__get_linked_tagnum(&G__DSTDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableDSTDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__DSTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DSTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DSTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DSTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DSTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__DSTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DSTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DSTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DSTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DSTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TDST */
static void G__setup_memvarTDST(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__DSTDictLN_TDST));
   { TDST *p; p=(TDST*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fServedBranches)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DSTDictLN_TDSTcLcLTBranch),-1,-1,1,"fServedBranches[220][6]=",0,"branches for served banks");
   G__memvar_setup((void*)((long)(&p->fBankType)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fBankType[220]=",0,"types of server banks");
   G__memvar_setup((void*)((long)(&p->fBankIndex)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fBankIndex[220]=",0,"indices of served banks");
   G__memvar_setup((void*)((long)(&p->fRowLength)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fRowLength[220]=",0,"lengths rows in served banks ");
   G__memvar_setup((void*)((long)(&p->fBankList)-(long)(p)),99,0,0,-1,-1,-1,1,"fBankList[220][8]=",0,"names of served banks");
   G__memvar_setup((void*)((long)(&p->fBankBranch)-(long)(p)),99,0,0,-1,-1,-1,1,"fBankBranch[220][8]=",0,"names of main served branches ");
   G__memvar_setup((void*)((long)(&p->fRowTotal)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fRowTotal[220]=",0,"no of rows in each bank for event	");
   G__memvar_setup((void*)((long)(&p->fDSTfile)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DSTDictLN_TDSTcLcLTFile),-1,-1,1,"fDSTfile=",0,"input file");
   G__memvar_setup((void*)((long)(&p->fBankTree)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DSTDictLN_TDSTcLcLTTree),-1,-1,1,"fBankTree=",0,"tree with bank data");
   G__memvar_setup((void*)((long)(&p->fBigBuff)-(long)(p)),67,0,0,-1,-1,-1,1,"fBigBuff=",0,"huge data buffer");
   G__memvar_setup((void*)((long)(&p->fDataStartAddr)-(long)(p)),67,0,0,-1,-1,-1,1,"fDataStartAddr=",0,"pointer within buffer");
   G__memvar_setup((void*)((long)(&p->fDataAddr)-(long)(p)),67,0,0,-1,-1,-1,1,"fDataAddr=",0,"ditto");
   G__memvar_setup((void*)((long)(&p->fServedBankNo)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fServedBankNo=",0,"no of banks being handled");
   G__memvar_setup((void*)((long)(&p->fEntry)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fEntry=",0,"counter for events");
   G__memvar_setup((void*)((long)(&p->fMaxEntry)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fMaxEntry=",0,"max no of events to be done");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DSTDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarDSTDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTDST(void) {
   /* TDST */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__DSTDictLN_TDST));
   G__memfunc_setup("TDST",319,G__DSTDict_174_0_1, 105, G__get_linked_tagnum(&G__DSTDictLN_TDST), -1, 0, 3, 1, 1, 0, 
"C - - 10 - - Y - - 0 - - "
"i - - 0 - -", "class cnstructor", (void*) NULL, 0);
   G__memfunc_setup("GetEvent",802,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", "main function to be called for each event", (void*) NULL, 1);
   G__memfunc_setup("StartServer",1157,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", "some init after class construction", (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__DSTDict_174_0_4, 85, G__get_linked_tagnum(&G__DSTDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TDST::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__DSTDict_174_0_5, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TDST::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__DSTDict_174_0_6, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TDST::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__DSTDict_174_0_7, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TDST::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__DSTDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__DSTDict_174_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__DSTDict_174_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TDST::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__DSTDict_174_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TDST::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__DSTDict_174_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TDST::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__DSTDict_174_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TDST::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TDST", 319, G__DSTDict_174_0_16, (int) ('i'), G__get_linked_tagnum(&G__DSTDictLN_TDST), -1, 0, 1, 1, 1, 0, "u 'TDST' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TDST", 445, G__DSTDict_174_0_17, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__DSTDict_174_0_18, (int) ('u'), G__get_linked_tagnum(&G__DSTDictLN_TDST), -1, 1, 1, 1, 1, 0, "u 'TDST' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncDSTDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalDSTDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcDSTDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__DSTDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__DSTDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__DSTDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__DSTDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__DSTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__DSTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DSTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__DSTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DSTDictLN_TRootBeer = { "TRootBeer" , 99 , -1 };
G__linked_taginfo G__DSTDictLN_TDST = { "TDST" , 99 , -1 };
G__linked_taginfo G__DSTDictLN_TDSTcLcLTBranch = { "TDST::TBranch" , 99 , -1 };
G__linked_taginfo G__DSTDictLN_TDSTcLcLTFile = { "TDST::TFile" , 99 , -1 };
G__linked_taginfo G__DSTDictLN_TDSTcLcLTTree = { "TDST::TTree" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableDSTDict() {
  G__DSTDictLN_TClass.tagnum = -1 ;
  G__DSTDictLN_TBuffer.tagnum = -1 ;
  G__DSTDictLN_TMemberInspector.tagnum = -1 ;
  G__DSTDictLN_TObject.tagnum = -1 ;
  G__DSTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__DSTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DSTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__DSTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DSTDictLN_TRootBeer.tagnum = -1 ;
  G__DSTDictLN_TDST.tagnum = -1 ;
  G__DSTDictLN_TDSTcLcLTBranch.tagnum = -1 ;
  G__DSTDictLN_TDSTcLcLTFile.tagnum = -1 ;
  G__DSTDictLN_TDSTcLcLTTree.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableDSTDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__DSTDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__DSTDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__DSTDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__DSTDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__DSTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__DSTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DSTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__DSTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DSTDictLN_TRootBeer);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DSTDictLN_TDST),sizeof(TDST),-1,62464,(char*)NULL,G__setup_memvarTDST,G__setup_memfuncTDST);
   G__get_linked_tagnum_fwd(&G__DSTDictLN_TDSTcLcLTBranch);
   G__get_linked_tagnum_fwd(&G__DSTDictLN_TDSTcLcLTFile);
   G__get_linked_tagnum_fwd(&G__DSTDictLN_TDSTcLcLTTree);
}
extern "C" void G__cpp_setupDSTDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupDSTDict()");
  G__set_cpp_environmentDSTDict();
  G__cpp_setup_tagtableDSTDict();

  G__cpp_setup_inheritanceDSTDict();

  G__cpp_setup_typetableDSTDict();

  G__cpp_setup_memvarDSTDict();

  G__cpp_setup_memfuncDSTDict();
  G__cpp_setup_globalDSTDict();
  G__cpp_setup_funcDSTDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDSTDict();
  return;
}
class G__cpp_setup_initDSTDict {
  public:
    G__cpp_setup_initDSTDict() { G__add_setup_func("DSTDict",(G__incsetup)(&G__cpp_setupDSTDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initDSTDict() { G__remove_setup_func("DSTDict"); }
};
G__cpp_setup_initDSTDict G__cpp_setup_initializerDSTDict;

