/********************************************************************
* src/DSTWriterDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/DSTWriterDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDSTWriterDict();
extern void G__cpp_setup_inheritanceDSTWriterDict();
extern void G__cpp_setup_typetableDSTWriterDict();
extern void G__cpp_setup_memvarDSTWriterDict();
extern void G__cpp_setup_globalDSTWriterDict();
extern void G__cpp_setup_memfuncDSTWriterDict();
extern void G__cpp_setup_funcDSTWriterDict();
extern void G__set_cpp_environmentDSTWriterDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/TDSTWriter.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DSTWriterDictLN_TClass;
extern G__linked_taginfo G__DSTWriterDictLN_TBuffer;
extern G__linked_taginfo G__DSTWriterDictLN_TMemberInspector;
extern G__linked_taginfo G__DSTWriterDictLN_TObject;
extern G__linked_taginfo G__DSTWriterDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__DSTWriterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DSTWriterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DSTWriterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DSTWriterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DSTWriterDictLN_TRootBeer;
extern G__linked_taginfo G__DSTWriterDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__DSTWriterDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DSTWriterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DSTWriterDictLN_TTree;
extern G__linked_taginfo G__DSTWriterDictLN_TFile;
extern G__linked_taginfo G__DSTWriterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__DSTWriterDictLN_TDSTWriter;

/* STUB derived class for protected member access */
