/********************************************************************
* src/RootBeerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/RootBeerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableRootBeerDict();
extern void G__cpp_setup_inheritanceRootBeerDict();
extern void G__cpp_setup_typetableRootBeerDict();
extern void G__cpp_setup_memvarRootBeerDict();
extern void G__cpp_setup_globalRootBeerDict();
extern void G__cpp_setup_memfuncRootBeerDict();
extern void G__cpp_setup_funcRootBeerDict();
extern void G__set_cpp_environmentRootBeerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/TRootBeer.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RootBeerDictLN_TClass;
extern G__linked_taginfo G__RootBeerDictLN_TBuffer;
extern G__linked_taginfo G__RootBeerDictLN_TMemberInspector;
extern G__linked_taginfo G__RootBeerDictLN_TObject;
extern G__linked_taginfo G__RootBeerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RootBeerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RootBeerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__RootBeerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RootBeerDictLN_addressBanks_t;
extern G__linked_taginfo G__RootBeerDictLN_TRootBeer;

/* STUB derived class for protected member access */
